[package]
name = "dita-core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
dita-design-system.workspace = true
leptos.workspace = true
leptos_ui.workspace = true
icons.workspace = true
leptos_router.workspace = true
